# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlignmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParallelCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParallelSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
                ('tgt', models.TextField()),
                ('parallel_corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.ParallelCorpus')),
            ],
        ),
        migrations.AddField(
            model_name='alignment',
            name='alignment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.AlignmentModel'),
        ),
        migrations.AddField(
            model_name='alignment',
            name='parallel_sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.ParallelCorpus'),
        ),
    ]
